# ⚙️ NumPy Operations

NumPy allows us to perform a wide range of operations on arrays, including arithmetic, logical, and universal mathematical functions. These operations can be broadly categorized into:

1. Basic Operations
2. Unary Operations
3. Universal Functions
4. Type Conversion

These operations are performed element-wise or across axes in a vectorized manner, making NumPy fast and efficient.

---

### 1. Basic Operations

In [74]:
import numpy as np

In [75]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([4, 5, 6, 7, 8, 9])

In [76]:
# Vector subtraction
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

Subtracts each element in `arr2` from `arr1`.

In [77]:
# b. Vector multiplication (element-wise)
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])

Multiplies each element in `arr1` with corresponding element in `arr2`.

In [78]:
# c. Scalar multiplication
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

Multiplies each element in `arr1` by 2.

In [79]:
# d. Element-wise comparison
arr1 > 3
arr2 > 3

array([ True,  True,  True,  True,  True,  True])

Returns a boolean array showing which elements are greater than 3.

### Matrix Dot Product

In [80]:
arr3 = np.arange(6).reshape(2, 3)
arr4 = np.arange(6, 12).reshape(3, 2)

In [81]:
# View matrices
arr3
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [82]:
# e. Matrix multiplication (dot product)
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

Performs matrix multiplication between `arr3` (2x3) and `arr4` (3x2). Result is a 2x2 matrix.

In [83]:
# f. Vector dot product
arr1.dot(arr2)

154

Computes dot product of 1D arrays (produces a scalar).

### Unary Operations

In [84]:
# Maximum Value
arr4.max()

11

In [85]:
# Minimum value
arr4.min()

6

In [87]:
# Minimum along columns and rows
arr4.min(axis=0)
arr4.min(axis=1)

array([ 6,  8, 10])

In [88]:
# Sum of all elements
arr4.sum()

51

In [93]:
# Sum column-wise
arr4.sum(axis=0)

array([24, 27])

In [94]:
# Mean
arr4.mean()

8.5

In [95]:
# Standard deviation
arr4.std()

1.707825127659933

These operations are useful for statistical insights into the array’s values.

### Universal Functions (UFuncs)

In [96]:
# Median
np.median(arr4)

8.5

#### Trigonometric Operations

In [97]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [98]:
np.cos(arr4)

array([[ 0.96017029,  0.75390225],
       [-0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ]])

In [99]:
np.tan(arr4)

array([[  -0.29100619,    0.87144798],
       [  -6.79971146,   -0.45231566],
       [   0.64836083, -225.95084645]])

In [100]:
# Exponential
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

These functions operate element-wise and are highly optimized for performance. Useful in mathematical modeling and transformations.

### Type Conversion

In [72]:
c = np.array([1.3, 3.6, 7.5])
print(f"Data type: {c.dtype}")

Data type: float64


In [101]:
# Convert to integer
c_int = c.astype(int)
print(f"Converted to int: {c_int}")

Converted to int: [1 3 7]
