# Introduction to NumPy

## What is NumPy?
##### NumPy (Numerical Python) is a low-level library written in **C** and **FORTRAN** for performing high-level mathematical functions efficiently in Python.
##### It uses **multidimensional arrays** and vectorized operations to make computations much faster than standard python lists.

## Why Use NumPy?

##### Python is inherently slower for mathematical operations due to its dynamic typing and object overhead. NumPy overcomes this limitation using:
- Contiguous memory blocks (like C arrays)
- Vectorized operations
- Broadcasting capabilities

##### This makes it the **core dependency** for many other libraries in the data science and machine learning ecosystem.

For example:
- **Pandas** is built on top of NumPy
- **Scikit-learn**, **TensorFlow**, **PyTorch**, and many others use NumPy internally


## Applications of NumPy

1. A powerful **N-dimensional array object** (`ndarray`)
2. Sophisticated functions with **broadcasting** capabilities
3. Integration with **C/C++ and FORTRAN** for performance
4. Built-in functions for:
   - Linear algebra
   - Fourier transforms
   - Random number generation
  
> ✅ Fun Fact: Almost every machine learning algorithm you’ll implement starts with NumPy arrays!


# Creating NumPy / N-Dimensional Arrays
In this section, we explore how to create different types of arrays using NumPy. Arrays are the core data structure in NumPy and come in 1-D, 2-D, or N-D (N-dimensional) forms.

## Importing NumPy and Checking Version
Before we start working with NumPy arrays, we first need to import the library and check the version we're using.

In [33]:
# Importing NumPy
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")

NumPy version: 1.26.1


## Creating Arrays
NumPy provides several ways to create arrays:

### 1. One-Dimensional Array

In [4]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [34]:
# Checking type
type(arr1)

numpy.ndarray

### 2. Two-Dimensional Array

In [35]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### 3. Array of Zeros

Create an array filled with zeros of a given shape.

In [18]:
arr3 = np.zeros((3,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 4. Array of Ones

Create an array filled with ones.

In [36]:
arr4 = np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

### 5. Identity Matrix

Creates a square identity matrix.

In [37]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 6. Array Using `arange()`

Creates evenly spaced values within a given interval.

In [38]:
arr6 = np.arange(10)
arr7 = np.arange(12,25)
arr8 = np.arange(10, 25, 2)
print(arr6)
print(arr7)
print(arr8)

[0 1 2 3 4 5 6 7 8 9]
[12 13 14 15 16 17 18 19 20 21 22 23 24]
[10 12 14 16 18 20 22 24]


### 7. Array Using `linspace()`

Creates evenly spaced numbers over a specified interval.

In [39]:
arr9 = np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

### 8. Copying Arrays

Use `.copy()` to make an independent copy of an array.

In [32]:
arr10 = arr9.copy()
arr10

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# NumPy Array properties and Attributes
Understanding the internal properties of NumPy arrays helps in better memory and performance optimization.

## 🔍 Common Array Attributes

1. **`shape`** – Gives the dimensions (rows, columns, etc.) of the array  
2. **`ndim`** – Number of dimensions (axes)  
3. **`size`** – Total number of elements in the array  
4. **`itemsize`** – Size (in bytes) of each element  
5. **`dtype`** – Data type of array elements  
6. **`astype()`** – Convert array to a different data type

---

Let's explore each of them with examples:

### 🔢 1D, 2D, and 3D Arrays

In [64]:
arr1 = np.array([1, 2, 3, 4, 5])  # 1D Array
arr2 = np.array([[1, 2, 3], [4, 55, 6]])  # 2D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # #D Array

### Shape of Arrays

In [65]:
print(f"Shape of arr1: {arr1.shape}")
print(f"Shape of arr2: {arr2.shape}")
print(f"Shape of arr3: {arr3.shape}")

Shape of arr1: (5,)
Shape of arr2: (2, 3)
Shape of arr3: (2, 2, 2)


### Number of Dimensions

In [67]:
print(f"Dimensions of arr1: {arr1.ndim}")
print(f"Dimensions of arr2: {arr2.ndim}")
print(f"Dimensions of arr3: {arr3.ndim}")

Dimensions of arr1: 1
Dimensions of arr2: 2
Dimensions of arr3: 3


### Total Number of Elements

In [69]:
print(f"Size of arr1: {arr1.size}")
print(f"Size of arr2: {arr2.size}")
print(f"Size of arr3: {arr3.size}")

Size of arr1: 5
Size of arr2: 6
Size of arr3: 8


### Data Types of Arrays

In [72]:
print("Data type of arr1:", arr9.dtype)
print("Data type of arr2:", arr10.dtype)
print("Data type of arr3:", arr11.dtype)

Data type of arr1: float64
Data type of arr2: float64
Data type of arr3: int32


### Memory Size per Element

In [73]:
print("Item size of arr11 (int32):", arr11.itemsize)
print("Item size of arr9 (float64):", arr9.itemsize)

Item size of arr11 (int32): 4
Item size of arr9 (float64): 8


### Changing Data Type using `astype()`

In [75]:
arr_float = arr11.astype('float')
print(arr_float)

[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


---

# Python Lists vs NumPy Arrays

When working with large numerical datasets, using NumPy arrays instead of Python lists has several advantages.

---

## Why Use NumPy Arrays Over Lists?

1. **Faster Execution**  
   NumPy uses optimized C libraries for computations.

2. **Convenient Syntax**  
   Operations like addition, multiplication, and broadcasting are simpler and vectorized.

3. **Less Memory Usage**  
   NumPy arrays consume less memory compared to lists due to fixed data types and contiguous memory blocks.

---

Let’s explore these differences with examples.

### Memory Usage Comparison

In [76]:
import numpy as np
import sys

list_a = range(100)
arr12 = np.arange(100)

In [77]:
# Memory used by Python list
print("Memory used by list_a:", sys.getsizeof(87) * len(list_a))  # size of int * 100

Memory used by list_a: 2800


In [78]:
# Memory used by NumPy array
print("Memory used by arr12:", arr12.itemsize * arr12.size)

Memory used by arr12: 400


### Speed Comparison

In [79]:
import time  # Importing the time module

In [82]:
# Python lists
x = range(100_000)
y = range(100_000, 200_000)

start_time = time.time()
c = [i + j for i, j in zip(x, y)]
print(f"Execution time using lists: {time.time() - start_time}")

Execution time using lists: 0.014124155044555664


In [83]:
# NumPy arrays
a = np.arange(100_000)
b = np.arange(100_000, 200_000)

start_time = time.time()
c = a + b
print(f"Execution time using NumPy: {time.time() - start_time}")

Execution time using NumPy: 0.0009942054748535156


#### let's use some bigger number too see the effected time gap
Using `100_000_000` and `200_000_000` 

In [86]:
# Python lists
x = range(100_000_000)
y = range(100_000_000, 200_000_000)

start_time = time.time()
c = [i + j for i, j in zip(x, y)]
print(f"Execution time using lists: {time.time() - start_time}")

Execution time using lists: 14.459115743637085


In [87]:
# NumPy arrays
a = np.arange(100_000_000)
b = np.arange(100_000_000, 200_000_000)

start_time = time.time()
c = a + b
print(f"Execution time using NumPy: {time.time() - start_time}")

Execution time using NumPy: 10.14659333229065


---

# 🔎 Indexing, Slicing, and Iteration in NumPy

Once you’ve created arrays, you'll often need to access, modify, or loop through elements. NumPy provides powerful tools for:

- Indexing: Accessing specific elements
- Slicing: Extracting sub-arrays
- Iteration: Looping through arrays

Let’s go through each of these step-by-step using a `6x4` array.

---

### Creating a 6x4 Array

In [112]:
arr12 = np.arange(24).reshape(6, 4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Indexing Rows

In [113]:
# Access the 3rd row (index 2)
arr12[2]

array([ 8,  9, 10, 11])

### Slicing Rows

In [114]:
# First 2 rows
arr12[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [115]:
## All rows (deep copy)
arr12[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Column Indexing and Slicing

In [116]:
# All rows, 3rd column
arr12[:, 2]

array([ 2,  6, 10, 14, 18, 22])

In [117]:
# All rows, 3rd column but keep it 2D
arr12[:, 2:3]

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [118]:
# All rows, columns 2 to 3
arr12[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

### Subarray Extraction (Matrix Slicing)

In [119]:
# Rows 3 & 4, Columns 2 & 3
arr12[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

In [120]:
# Last two rows, last two columns
arr12[4:6, 2:4]

array([[18, 19],
       [22, 23]])

### Iterating Over Rows

In [121]:
# Row-wise iteration
for row in arr12:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


### Iterating over all Elements

In [122]:
# Element-wise iteration
for elem in np.nditer(arr12):
    print(elem)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
