# 📘 Section: Reshaping, Stacking, Splitting & Indexing in NumPy

### 🔄 1. Reshaping NumPy Arrays

In [2]:
import numpy as np

In [3]:
arr4 = np.array([[6, 7], [8, 9], [10, 11]])

We start with a 2D array of shape (3, 2).

In [4]:
arr4.ndim

2

Returns the number of dimensions: `2` (indicating a matrix)

#### 1. `ravel()` - Flatten the Array

In [5]:
arr4.ravel()

array([ 6,  7,  8,  9, 10, 11])

Converts a multi-dimensional array into a **flattened 1D array**.


#### b. `transpose()` - Transpose the Array

In [6]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

Swaps rows with columns. Transforms shape from (3, 2) → (2, 3).

#### 2. Stacking Arrays

In [7]:
arr3 = np.array([[0, 1, 2], [3, 4, 5]])
arr5 = np.arange(12, 18).reshape(2, 3)

In [8]:
# Horizontal stacking
np.hstack((arr3, arr5))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

Stacks arrays **side by side** (column-wise), must have the same number of rows.

In [9]:
# Vertical stacking
np.vstack((arr3, arr5))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

Stacks arrays **on top of each other** (row-wise), must have the same number of columns.

### 3. Splitting Arrays

In [11]:
# Horizontal splitting
np.hsplit(arr3, 1)

[array([[0, 1, 2],
        [3, 4, 5]])]

`hsplit`: Splits array into sub-arrays **horizontally**

In [12]:
# Vertical splitting
np.vsplit(arr5, 2)

[array([[12, 13, 14]]), array([[15, 16, 17]])]

`vsplit`: Splits array into sub-arrays **vertically**

### 4. Fancy Indexing

In [13]:
arr8 = np.arange(24). reshape(6, 4)

In [14]:
# fancy Indexing to select specific rows
arr8[[0, 2, 4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [15]:
arr8[[0, 5, 4]]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [16, 17, 18, 19]])

Allows you to access **multiple non-consecutive rows** (or columns) using a list of indices.

### 5. Indexing Using Boolean Arrays

In [16]:
arr = np.random.randint(low=1, high=100, size=20).reshape(4, 5)

In [17]:
# Boolean condition on whole array
arr > 5

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True,  True]])

Generates a Boolean array with `True` for elements satisfying the condition.

#### Filtering with conditions

In [18]:
arr[arr > 5]

array([75, 20, 53, 68, 97, 78, 81, 97, 20, 66, 63,  8, 29, 55, 22, 51, 65])

Filters and returns only those values which are `> 5`

#### Multiple Conditions

In [20]:
arr[(arr > 50) & (arr % 2 != 0)]

array([75, 53, 97, 81, 97, 63, 55, 51, 65])

Combines multiple conditions using bitwise `&`. Returns odd numbers greater than 50.

#### Modify with Boolean Indexing

In [23]:
arr[(arr > 50) & (arr % 2 != 0)] = 0
arr

array([[ 0,  2, 20,  0, 68],
       [ 0, 78,  0,  0, 20],
       [66,  0,  8,  3, 29],
       [ 1,  0, 22,  0,  0]])

Replaces all odd numbers greater than 50 with `0`. Boolean indexing is also used for **in-place modifications**.